config/routes.rb
Rails.application.routes.draw do
  resources :class_statuses
  resources :class_lists
  resources :products do
  # resources :articles do
	resources :reviews, only: [:create]
  end
  # resources :comments
  # resources :articles
  devise_for :users
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'tests#index'
  # root 'products#index'
  root 'class_lists#index'
	
end

app/controllers/class_statuses_controller.rb
class ClassStatusesController < ApplicationController
  before_action :set_class_status, only: [:show, :edit, :update, :destroy]

  # GET /class_statuses
  # GET /class_statuses.json
  def index
    @class_statuses = ClassStatus.all
  end

  # GET /class_statuses/1
  # GET /class_statuses/1.json
  def show
  end

  # GET /class_statuses/new
  def new
    @class_status = ClassStatus.new
  end

  # GET /class_statuses/1/edit
  def edit
  end

  # POST /class_statuses
  # POST /class_statuses.json
  def create
    @class_status = ClassStatus.new(class_status_params)

    respond_to do |format|
      if @class_status.save
        format.html { redirect_to @class_status, notice: '강의 신청이 완료되었습니다.' }
        format.json { render :show, status: :created, location: @class_status }
      else
        format.html { render :new }
        format.json { render json: @class_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_statuses/1
  # PATCH/PUT /class_statuses/1.json
  def update
    respond_to do |format|
      if @class_status.update(class_status_params)
        format.html { redirect_to @class_status, notice: 'Class status was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_status }
      else
        format.html { render :edit }
        format.json { render json: @class_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_statuses/1
  # DELETE /class_statuses/1.json
  def destroy
    @class_status.destroy
    respond_to do |format|
      format.html { redirect_to class_statuses_url, notice: 'Class status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_status
      @class_status = ClassStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def class_status_params
      params.require(:class_status).permit(:user_id, :class_list_id)
    end
end

app/helpers/class_statuses_helper.rb
module ClassStatusesHelper
end

app/views/class_statuses/_form.html.erb
<%= form_with(model: class_status, local: true) do |form| %>
  <% if class_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_status.errors.count, "error") %> prohibited this class_status from being saved:</h2>

      <ul>
        <% class_status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :class_list_id %>
    <%= form.text_field :class_list_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_statuses/edit.html.erb
<h1>Editing Class Status</h1>

<%= render 'form', class_status: @class_status %>

<%= link_to 'Show', @class_status %> |
<%= link_to 'Back', class_statuses_path %>

app/views/class_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Statuses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Class list</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_statuses.each do |class_status| %>
      <tr>
        <td><%= class_status.user_id %></td>
        <td><%= class_status.class_list_id %></td>
        <td><%= link_to 'Show', class_status %></td>
        <td><%= link_to 'Edit', edit_class_status_path(class_status) %></td>
        <td><%= link_to 'Destroy', class_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class Status', new_class_status_path %>

app/views/class_statuses/new.html.erb
<h1>New Class Status</h1>

<%= render 'form', class_status: @class_status %>

<%= link_to 'Back', class_statuses_path %>

app/views/class_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @class_status.user_id %>
</p>

<p>
  <strong>Class list:</strong>
  <%= @class_status.class_list_id %>
</p>

<%= link_to 'Edit', edit_class_status_path(@class_status) %> |
<%= link_to 'Back', class_statuses_path %>