config/routes.rb
Rails.application.routes.draw do
  resources :class_statuses
  resources :class_lists
  resources :products do
  # resources :articles do
	resources :reviews, only: [:create]
  end
  # resources :comments
  # resources :articles
  devise_for :users
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'tests#index'
  # root 'products#index'
  root 'class_lists#index'
	
end

app/models/class_list.rb
class ClassList < ApplicationRecord
	has_many :class_statuses
	has_many :users, :through => :class_statuses
end

app/controllers/class_lists_controller.rb
class ClassListsController < ApplicationController
  before_action :set_class_list, only: [:show, :edit, :update, :destroy]

  # GET /class_lists
  # GET /class_lists.json
  def index
    @class_lists = ClassList.all
  end

  # GET /class_lists/1
  # GET /class_lists/1.json
  def show
  end

  # GET /class_lists/new
  def new
    @class_list = ClassList.new
  end

  # GET /class_lists/1/edit
  def edit
  end

  # POST /class_lists
  # POST /class_lists.json
  def create
    @class_list = ClassList.new(class_list_params)

    respond_to do |format|
      if @class_list.save
        format.html { redirect_to @class_list, notice: 'Class list was successfully created.' }
        format.json { render :show, status: :created, location: @class_list }
      else
        format.html { render :new }
        format.json { render json: @class_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_lists/1
  # PATCH/PUT /class_lists/1.json
  def update
    respond_to do |format|
      if @class_list.update(class_list_params)
        format.html { redirect_to @class_list, notice: 'Class list was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_list }
      else
        format.html { render :edit }
        format.json { render json: @class_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_lists/1
  # DELETE /class_lists/1.json
  def destroy
    @class_list.destroy
    respond_to do |format|
      format.html { redirect_to class_lists_url, notice: 'Class list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_list
      @class_list = ClassList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def class_list_params
      params.require(:class_list).permit(:c_name, :c_account)
    end
end

app/helpers/class_lists_helper.rb
module ClassListsHelper
end

app/views/class_lists/_form.html.erb
<%= form_with(model: class_list, local: true) do |form| %>
  <% if class_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_list.errors.count, "error") %> prohibited this class_list from being saved:</h2>

      <ul>
        <% class_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :c_name %>
    <%= form.text_field :c_name %>
  </div>

  <div class="field">
    <%= form.label :c_account %>
    <%= form.number_field :c_account %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_lists/edit.html.erb
<h1>Editing Class List</h1>

<%= render 'form', class_list: @class_list %>

<%= link_to 'Show', @class_list %> |
<%= link_to 'Back', class_lists_path %>

app/views/class_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>강의 리스트</h1>

<table>
  <thead>
    <tr>
      <th>강의명</th>
      <th>수강인원현황</th>
      <th>비고</th>
    </tr>
  </thead>

  <tbody>
    <% @class_lists.each do |class_list| %>
      <tr>
        <td><%= class_list.c_name %></td>
		<td><%= ClassStatus.where(class_list_id: class_list.id).size %> / <%= class_list.c_account %></td>
		<td><%= button_to "강의신청", class_statuses_path(class_status: { user_id: current_user.id, class_list_id: class_list.id } ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class List', new_class_list_path %>

app/views/class_lists/new.html.erb
<h1>New Class List</h1>

<%= render 'form', class_list: @class_list %>

<%= link_to 'Back', class_lists_path %>

app/views/class_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>C name:</strong>
  <%= @class_list.c_name %>
</p>

<p>
  <strong>C account:</strong>
  <%= @class_list.c_account %>
</p>

<%= link_to 'Edit', edit_class_list_path(@class_list) %> |
<%= link_to 'Back', class_lists_path %>